### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#11]
Set Up Virtual Machine

should run:

- [x]  atom with mope plugin 
- [x] mope server
- [x] openmodelica 
- [x]  development version of mope server
- [x] Working IntelliJ

should contain:

1. modelica example models

What else do we need?

Environment Documentation: https://github.com/MopeSWTP-SS21/MopeSWTP/wiki/Development-Environment

**Comment by manuEbg** [comment]
Current interim status:

https://drive.google.com/file/d/10J96ffiJPJwVgHHKGgxga-5XQzDTL4WE/view?usp=sharing 

Version 2 (mobe-server 0.7.2)

https://drive.google.com/file/d/1GrB5qel_-gFPMwlehykjKQt4rx0fX7uR/view?usp=sharing

**Comment by manuEbg** [comment]
currently I share the OVA via my google drive. But i only have 15gb of storage and the current OVA is almost 14gb.

I think its quite possible that it will become even larger in the future. So we need a better place to share the VM.

@CSchoel Do you have an Idea what this place could be?

**Comment by CSchoel** [comment]
Other alternatives:

[HessenBox](https://www.thm.de/its/services/softwarelizenzen/softwareangebot/hessenbox.html)
[MNI NextCloud](https://nextcloud.mni.thm.de/) (only accessible via VPN)

**Comment by manuEbg** [comment]
New VM Version is available on HessenBox
https://hbx.fhhrz.net/getlink/fiFkRUPHw1dQd8ogipjb18HU/POP%21_SWTP%20v4.ova

**Comment by CSchoel** [comment]
@manuEbg The location of the development environment should be documented somewhere. Maybe the wiki?

**Comment by manuEbg** [comment]
> 
> 
> @manuEbg The location of the development environment should be documented somewhere. Maybe the wiki?

I have updated the wiki

**Comment by manuEbg** [comment]
I managed to hit some Breakpoints in the Mope-server. ☺️
new ova is currently uploading...
