### ISSUE TITLE
Proposal: Use Element.thm.de for quick communication

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#13]
I think the project would benefit from a more direct communication channel between us than just email and issues. It was recently brought to my attention that we have a matrix server for end-to-end-encrypted chats at the THM at https://element.thm.de. The authentication is done via LDAP with your normal THM credentials.

I have created a group for the SWTP and invited you (which seemed to be possible even if you do not have an account yet). Let me know, what you think. :smile:

**Comment by manuEbg** [comment]
Propsal accepted : )
