### ISSUE TITLE
FYI: ZenHub for more Scrum support in GitHub?

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#16]
I just stumbled upon [ZenHub](https://help.zenhub.com/support/solutions/articles/43000010778-what-is-zenhub-an-intro-to-zenhub-in-github) which essentially is a browser extension that facilitates agile workflows - especially scrum - using the basic features of GitHub. This gives, for example, support for Epics and Burndown Charts. I'll leave this here as an issue so that you can decide whether you want to use it or not. Let me know your thoughts.

**Comment by IlmarB** [comment]
Thanks for the advice. We did a review in our last daily-scrum-meeting and it was pretty intuitive on the first try. We will have a deeper look on this one until we meet a final decision.

**Comment by CSchoel** [comment]
Currently the Project seems to be included in two separate ZenHub workspaces (MoPe and SWTP). Is this by accident or deliberate? If you settle for a workflow using ZenHub, I would be very glad if you could document your usage of ZenHub somewhere. Maybe in the Wiki?

**Comment by IlmarB** [comment]
We have updated our wiki with an entry where we explain our future usage of ZenHub. See here: https://github.com/MopeSWTP-SS21/MopeSWTP/wiki/ZenHub-deployment
