### ISSUE TITLE
Allow english questions at KoBIS presentation

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#25]
Fabian, the organizer of the KoBIS, asked if he could advertise the project presentation at the Giessen Graduate Centre for the Life Sciences (GGL). Usually this would require the presentation to be in English language. Currently, however, it would also suffice if questions in English were allowed after the presentation. Would this be OK for you?

**Comment by manuEbg** [comment]
We dont have a problem with giving the presentation in English. Also no problem with being asked questions in English, and answering them in English.
However, the English wont be close to perfect and certainly the presentation will lose some quality.
But we're totally fine with that in case it wont affect the grading in a bad way.

If it's really just English questions from some non-German speaking listeners, it's definitely not a problem.

**Comment by CSchoel** [comment]
I would love it if you could hold the presentation in English. Broken English is perfectly fine (and actually more the norm than not on international conferences :wink: ). More on this in the Matrix chat, since it affects grading.

**Comment by CSchoel** [comment]
@manuEbg, @IlmarB, @CptKaNe I still need your input on this. Please drop by in the matrix server and let me know your final decision. :smile:

**Comment by manuEbg** [comment]
We decided to give the Presentation in English!
