### ISSUE TITLE
Importing LSPConsole into MopeSWTP

### ISSUE THREAD

**Issue by CptKaNe** [MopeSWTP-SS21/MopeSWTP#41]
As we discussed in our meeting i searched for the easiest way to migrate the LSPConsole repo into this one, so
I thought of maybe adding our LSPConsole repo as a new branch to this repo and then simply merge that branch into main.

According to this post [https://stackoverflow.com/a/1684694/16164446](url) this should be no problem, even if the issue in this thread is about migrating a subtree into a new repository. Nevertheless, i did not want to try all by myself without your thoughts.

**Comment by manuEbg** [comment]
I think i would go for this approach (
1. clone lspconsole repo
2. checkout all branches (latest version :) ) 
3. change the git remote to MopeSWTP repo
4. (maybe change projectname?)
5. and push all branches
6. set (new) main branch as default (in github)
7. merge licence from old main into new main and maybe dev 
8. delete old main
