### ISSUE TITLE
continuous delivery

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#43]
I think it would be really cool If we would add a GithubAction, 
that generates both our Jar-Files and uploades them somewhere:)

What do you all think?

**Comment by CSchoel** [comment]
Big :+1: . That would make testing so much easier. You even do not have to find a server to upload the files. You can simply use [GH Action artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts).

For finished prototypes I would suggest to generate releases based on git tags. You can add a separate action to the repo that only reacts on new tags that are pushed to GitHub and then generates a release draft via, for example, [softprops/action-gh-release](https://github.com/softprops/action-gh-release).

**Comment by manuEbg** [comment]
see #106
