### ISSUE TITLE
Run Testsuite with ExampleModels

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#49]
- Add models to repository/project
- Tests use relative paths to the models

**Comment by CSchoel** [comment]
@CptKaNe  This issue has not received any updates in the last week. What is your status?

**Comment by CptKaNe** [comment]
due to several issues last week concerning my health i was not able to work on any issue. I just arrived from the medic and will put my effort in the issues the remaining four days. i am sorry about that.
