### ISSUE TITLE
Einverständniserklärung für externes Projektmanagement

### ISSUE THREAD

**Issue by IlmarB** [MopeSWTP-SS21/MopeSWTP#5]
Ich brauche von Ihnen allen eine Einverständniserklärung, dass das Projekt als Teil einer Lehrveranstaltung der THM trotzdem hier auf GitHub gehostet werden kann.

Dazu werde ich ein PDF-Dokument erstellen, was mir bitte jeder von Ihnen unterschrieben per Mail zurücksendet.

**Comment by IlmarB** [comment]
PDF ist erstellt und steht zum Download bereit: https://homepages.thm.de/~cslz90/kurse/swtp21/Einverst%c3%a4ndniserkl%c3%a4rung.pdf

**Comment by CptKaNe** [comment]
I sent him mine.

**Comment by manuEbg** [comment]
@IlmarB Ich glaube die Beschreibung des Issues ist die Falsche

**Comment by manuEbg** [comment]
> 
> 
> I sent him mine.

me too

**Comment by IlmarB** [comment]
I just did
