### ISSUE TITLE
Apply Testsuite to MulticlientBranche

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#50]
Currently the Testsuite wont run in the MultiClientBranche (and successive branches...).
This needs to be fixed

**Comment by CSchoel** [comment]
@CptKaNe  This issue has not received any updates in the last week. What is your status?

**Comment by CptKaNe** [comment]
due to several issues last week concerning my health i was not able to work on any issue. I just arrived from the medic and will put my effort in the issues the remaining four days. i am sorry about that.

**Comment by manuEbg** [comment]
Since this is a high priority Issue , I am going to take care of it so we can move on.
