### ISSUE TITLE
Connect VSCode client to LspMopeServer

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#51]
The title says it all...

Following Issues might be:

- Display Errors
- Check Model
- Code Completion

**Comment by manuEbg** [comment]
Note: https://github.com/MopeSWTP-SS21/MopeSWTP/issues/21#issuecomment-864084062

**Comment by CSchoel** [comment]
Please notify me, when you have done the first tests, connecting to the VS Code client as I would like to close #40 , once I can be sure that the implementation is correct. Any further problems concerning specific features should then become separate issues in [MopeSWTP-SS21/vs-code-client](https://github.com/MopeSWTP-SS21/vs-code-client).

**Comment by manuEbg** [comment]
I have not worked on this Issue yet.

**Comment by manuEbg** [comment]
I just connected the VsCode Client to our MopeServerJar.
This was pretty easy because i just had to follow the steps in the readme.
The only problem i had was that pressing F5 just triggered a build but didn't open another vscode window with the Extension running...
Propably because i forgot the  Save Workspace As in this step:
* Create a VS Code project that has the working copy of this repository as the only workspace folder (this is needed, because the repo contains a `.vscode` folder with settings that are required to test the extension). You can do this with the following steps:
    * Open a new window in VS code.
    * Select File -> Add folder to workspace ...
    * Add the folder containing this repository and save the workspace using File -> Save Workspace As ...


I then tried `File -> Open Folder` and selected the VsCodeClientRepo. This worked:)

After Connecting to the Server i received a Message "Hallo vom Server" and could see that the InitializationRequest was triggered.

However none of the other Commands worked.
loadModel is connected to this https://github.com/MopeSWTP-SS21/MopeSWTP/issues/85 
Completion probably didn't work because our Mope Server does not publish any capabilities... 

So the next Step for me is to publish some Server Capabilities.
There will be a new Issue for this (see https://github.com/MopeSWTP-SS21/MopeSWTP/issues/91)

**Comment by manuEbg** [comment]
After Publishing CompletionCapabilities, I managed to complete Something:)
![Completion](https://user-images.githubusercontent.com/37020423/124385798-8d33e580-dcd7-11eb-9c5b-5a460ec6610f.PNG)

However there are some Major Issues:(
1. My ["SymbolLimiter"](https://github.com/MopeSWTP-SS21/MopeSWTP/blob/a007ade825b64e339bec1ede8fe2aa00f2363c4e/src/main/java/Server/CompletionProvider.java#L30) does not work as expected because it does not stop at Whitespaces...
2. Much bigger Problem: The Server can only read stuff from the File if it is saved. This makes Completion not very user friendly...

**Comment by manuEbg** [comment]
I think we need to implement the [DidChangedTextDocument-Notification](https://microsoft.github.io/language-server-protocol/specification.html#textDocument_didChange) and [DidOpenTextDocument-Notification](https://microsoft.github.io/language-server-protocol/specification.html#textDocument_didOpen) to maintain some _ShadowFiles_ for the Server.

**Comment by CSchoel** [comment]
Yeah, I think you are right on track with your analysis. :+1:  Keep in mind that you might have to tell the client how you want to [synchronize unsaved document updates](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_synchronization_sc).

**Comment by manuEbg** [comment]
After the Workaround or Fix https://github.com/MopeSWTP-SS21/MopeSWTP/issues/85#issuecomment-875656571 i was able to load a Model from VSCode. 
And i was able to not load a Model but see Diagnostics:) Somehow there seems to be a _LineCharacterConfusionIssue_... ![Diagnostics](https://user-images.githubusercontent.com/37020423/124779011-b9529f00-df41-11eb-87b8-b34b923afec1.PNG)

**Comment by CSchoel** [comment]
Can you double-check ...

* which file is loaded by the OMC and what are its contents,
* and what is the raw error message reported by the OMC?

On my machine, OMShell reports the following:

```
>> loadModel(SyntaxError); getErrorString()
false
"[/home/cslz90/Documents/Promotion/code/MoST/test/res/SyntaxError.mo:6:3-6:3:writable] Error: Missing token: SEMICOLON
Error: Failed to load package SyntaxError (default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/cslz90/.openmodelica/libraries/:/home/cslz90/Documents/Promotion/code/MoST/test/res.
"
```

This is what I would expect, since the error is on the first token that comes after the position where the semicolon should be (6:3).

Actually, now that I see the numbers... could it be that you just have a one-off error in your line and column indices?

**Comment by manuEbg** [comment]
You are right. The Error is in fact located in 6:3.
The Diagnostic published by the MopeServer also contains 6:3
```
DiagnosticLocation: /home/swtp/modelica/exampleModels/SyntaxError.mo
Diagnostics: 
Diagnostic [
  range = Range [
    start = Position [
      line = 6
      character = 3
    ]
    end = Position [
      line = 6
      character = 3
    ]
  ]
  severity = Error
  code = null
  codeDescription = null
  source = null
  message = "Error: Missing token: SEMICOLON\n"
  tags = null
  relatedInformation = null
  data = null
]
```
The VSCodeClient seems to increment the received Position
