### ISSUE TITLE
Document Modelica Specific JSON-RPC calls

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#52]
Write some kind of Documentation for all the Modelica specific JSON-RPC calls, which are defiend in the [ModelicaService](https://github.com/MopeSWTP-SS21/MopeSWTP/blob/main/src/main/java/Server/ModelicaService.java) 

I think the right place for Docs would be our [Wiki](https://github.com/MopeSWTP-SS21/MopeSWTP/wiki)

 The Docs should help developers who want to create ClientApplications .

This would Require
- Information about the Methodname (ex.: method: ‘textDocument/didOpen’)
- Information about Parameters
- Information about Return values
- Of course Informations about what this method is intended to do.
- maybe what scripting api calls it uses

I think you should create a single Issue for every  JSON-RPC call.
This would allow us to 
- tell u about new Json Rpc calls
- maybe have a discussion about a specific call
- take better track of project progress:)

**Comment by manuEbg** [comment]
Maybe the [Official LSP-Specification](https://microsoft.github.io/language-server-protocol/) can serve as a source of inspiration

**Comment by IlmarB** [comment]
I am working on it. See [issue#63](https://github.com/MopeSWTP-SS21/MopeSWTP/issues/63)

**Comment by IlmarB** [comment]
Documentation for JSON RPC Calls

- [x] checkModel
- [x] loadModel
- [x] loadFile
- [x] initializeModel
- [x] getModelicaPath
- [x] addModelicaPath
- [x] getCompilerVersion

**Comment by IlmarB** [comment]
I have finished this task

**Comment by manuEbg** [comment]
> 
> 
> I have finished this task

If you finished this task, you probably should close this Issue:)
