### ISSUE TITLE
Readme Jar

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#55]
Add some Info about how to build the Server and Console Jar
Check [this](https://github.com/MopeSWTP-SS21/LspConsole/issues/9#issuecomment-859576660) out

**Comment by CSchoel** [comment]
@IlmarB This issue has not received any updates in the last week. What is your status?

**Comment by IlmarB** [comment]
Have nothing done for that yet

**Comment by IlmarB** [comment]
should be done. I have added the instructions to the existing Readme.md. You can find the recent version on branch "jar"

**Comment by manuEbg** [comment]
I am not quite sure about step 1. 
Why do you need to add the tasks? aren't they already in the build.gradle File?
Also I don't think it is necessary to create a separate Branch for some changes to the Readme 😄

**Comment by IlmarB** [comment]
thanks for the feedback. I think you are right. From the end-user's perspective it makes no sense. 
I had a conflict while uploading and I was to lazy to fix this which resulted in creating a new branch. I will fix this too, sigh 😅

**Comment by IlmarB** [comment]
Done - modified and uploaded (currently on branch `feature/shutDown_v1`)
