### ISSUE TITLE
Readme Console Commands

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#56]
Provide more Informations about the possible Commands that can be used in the ConsoleApp.

- Some Infos About what this Command does
- Some Infos about the Parameters
- Maybe an Example.

Of course @CptKaNe and myself will supply you with more commands in the future:)

I think this is closely related to https://github.com/MopeSWTP-SS21/MopeSWTP/issues/52

**Comment by IlmarB** [comment]
I have worked on this in [#64](https://github.com/MopeSWTP-SS21/MopeSWTP/issues/64)

**Comment by CSchoel** [comment]
Is there a reason why #64 is a separate issue? As far as I can see, the two issues seem to cover the exact same content.

**Comment by IlmarB** [comment]
Yes almost the same yet different. There are 2 wiki entries for each issue.
I am closing this issue since it's done.
