### ISSUE TITLE
Implement getDoc JSON-RPC

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#59]
We need JSON-RPC with whom it is possible to request the HTML-Documentation of a loaded Modelica class

- [x] Find out how to get the HtmlDocs of a class
- [x] Implement getDoc RPC
- [x] Implement getDoc command in ConsoleApp

**Comment by manuEbg** [comment]
@CptKaNe  Im sorry that i have assigned you. But I realized im the Scrum master and probably have enough to do... 
This does not have to be set in stone yet:)

**Comment by CSchoel** [comment]
Tip: You should be able to just use the API function [`getDocumentationAnnotation()`](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#getdocumentationannotation) for this.

**Comment by CSchoel** [comment]
@CptKaNe  This issue has not received any updates in the last week. What is your status?

**Comment by CptKaNe** [comment]
due to several issues last week concerning my health i was not able to work on any issue. I just arrived from the medic and will put my effort in the issues the remaining four days. i am sorry about that.

**Comment by CSchoel** [comment]
@CptKaNe I hope you are feeling better now. Can you keep us posted about the status of your issues? It has been another week without update.
