### ISSUE TITLE
Problemdomäne kennenlernen

### ISSUE THREAD

**Issue by IlmarB** [MopeSWTP-SS21/MopeSWTP#6]
Ich möchte, dass sich jeder aus dem Team bis nächste Woche Freitag mit dem OpenModelica Compiler und dem bestehenden Mo|E-Projekt auseinandersetzt.

Insbesondere beinhaltet das die folgenden Aufgaben:

* [OpenModelica](https://openmodelica.org/) installieren
* [Lotka-Volterra-Modell](https://mbe.modelica.university/components/components/population/) "von Hand" nachbauen in OMEdit
* Simulation des LV-Modells über OMEdit
* Simulation des LV-Modells über OMShell
* [Mo|E](https://github.com/THM-MoTE/mope-server) + [Atom-Plugin](https://github.com/THM-MoTE/mope-atom-plugin) installieren
* [Erweiterung von LV mit Wölfen](https://mbe.modelica.university/components/components/population/#adding-wolves) (ohne Grafik) in Atom bauen

**Comment by CSchoel** [comment]
Just an Idea: You could add your three different LV implementations to the repository. They could serve as test examples later.

**Comment by manuEbg** [comment]
I added a new repository which will contain our Lotka-Volterra Models.
( https://github.com/MopeSWTP-SS21/LotkaVolterra )

**Comment by manuEbg** [comment]
Maybe not 100%... but the basics are known

**Comment by manuEbg** [comment]
> 
> 
> Maybe not 100%... but the basics are known
