### ISSUE TITLE
Creating a wiki-entry for console commands documentation

### ISSUE THREAD

**Issue by IlmarB** [MopeSWTP-SS21/MopeSWTP#64]
First step is listing all the commands our application has. After that describing each one specifically.

**Comment by IlmarB** [comment]
To document my workflow I have created a task list

- [x] 1. Initialize server
- [x] 2. Get compiler version
- [x] 3. Load File
- [x] 4. Load Model
- [x] 5. Check Model
- [x] 6. Initialize Model
- [x] 7. Add a folder to ModelicaPath
- [x] 8. Show ModelicaPath
- [x] 9. Exit

For the documentation see [here](https://github.com/MopeSWTP-SS21/MopeSWTP/wiki/Console-Command-Documentation)

**Comment by IlmarB** [comment]
I have finished the documentation. Could you guys @manuEbg and @manuEbg review it please? Any hints or critisim are welcome :)

**Comment by CSchoel** [comment]
Not sure if the second @manuEbg is supposed to be @CptKaNe or me, so I'll just chime in. :laughing: 

I think the level of detail and the descriptions are fine. There are a few language-related issues ("to tell the server start" is missing a "to", "look on" -> "look at", "see that output" -> "see this output"), which are not critical. For those I suggest, you can just use LanguageTool, which should be able to find most of these simple grammatical errors automatically. The quickest way is to use the web service provided at https://languagetool.org/de , but for a frictionless workflow I would suggest to use a plugin for the editor/IDE of your choice. I use [LTeX](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex) for VS Code. For you, the JetBrains plugin [Grazie](https://plugins.jetbrains.com/plugin/12175-grazie/) may be interesting.

Regarding the content I would like a little more structure. Either you can separate the commands with sub-headings (advantage: on GitHub you should be able to directly link to subheadings in the wiki), or an enumerated list (advantage: would have the same structure as the main menu, disadvantage: multiple paragraphs inside a list item are possible in markdown, but a little tricky).

Additionally, you could again specify that `loadModel`/`checkModel`/`instantiateModel` require a fully qualified Modelica model name. Also you seem to have confused the name [`instantiateModel`](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#instantiatemodel) with `initializeModel`.

**Comment by IlmarB** [comment]
Okay, thanks for the feedback! (Yep, second manueEbg was supposed to be CptKaNe) 
Correction is ongoing!

**Comment by manuEbg** [comment]
After latest Merges there should be a new ConsoleCommand `complete`.
Please add this to the docs as well

**Comment by IlmarB** [comment]
Roger that

**Comment by IlmarB** [comment]
I have done it halfway. Cannot figure out if an OMC scripting command was used

**Comment by manuEbg** [comment]
You can find the  used OMC Scripting Commands in our OMCAdapter.java

These Commands are sent via the Java-OMC-Api and ZMQ-Messages to the Compiler
