### ISSUE TITLE
Readme of this project tells to download the (outdated?) LspConsole project

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#65]
It seems that the README file was copied from the LSPConsole project without the necessary adjustments.

**Comment by IlmarB** [comment]
Done - it is up to date now on the branch `feature/shutDown`

**Comment by CSchoel** [comment]
There is no branch `feature/shutDown`, but there are  `feature/cfgAndShutDown`, `feature/cfgAndShutdown`, `feature/shutDown_v1`, and `shutdown_v2`, which is a little confusing.
