### ISSUE TITLE
Fork oder Neustart?

### ISSUE THREAD

**Issue by IlmarB** [MopeSWTP-SS21/MopeSWTP#7]
Bis zum nächsten Treffen am Freitag sollte das Team entscheiden, ob Sie ihre Arbeit auf dem [bestehende Mo|E-Projekt](https://github.com/THM-MoTE/mope-server) aufbauen oder es von Grund auf neu entwickeln wollen.

**Comment by manuEbg** [comment]
Since Nicolas Bachelor Thesis seems to be very clean and professional and because of all the functionality that is already working, we decided to Fork the Project.
