### ISSUE TITLE
TimeoutException when connecting to VS Code client

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#74]
When I connect the VS code client to the current server version, [this line](https://github.com/MopeSWTP-SS21/MopeSWTP/blob/7e949e1bf94de85b7c925972eeef3db53299ec7c/src/main/java/Server/MopeLSPServerLauncher.java#L60) throws a TimeoutException. What is the purpose of this line?

**Comment by manuEbg** [comment]
there is no purpose. It was used to get a bit familiar with RPC.
This will be closed when we merge the multiclientBranche.

**Comment by manuEbg** [comment]
Since I merged the MultiClientBranch and didn't have any Problems connecting the VsCodeClient to our MopeServer i`m closing this Issue
