### ISSUE TITLE
OMC is never shut down

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#76]
## Steps to reproduce

* Start server
* Start console client, connect to server
* Send initialize (option 1)
* Send exit (option 9)
* Shutdown server process by pressing enter

## Expected behavior

The OMC process started by the server should be shut down.

## Actual behavior

The OMC process is still running.

This is probably relevant for #53 .

**Comment by IlmarB** [comment]
right now the omc is shutdown by pressing enter, which as I did understand, should not be the case. I think the server shutdown should be the last step without any user interaction after he has pressed "9"

**Comment by CSchoel** [comment]
I'm not sure if sending the exit call to the server must be the last step here, since you have a multi-client server (see #53).

What is more important is that even when the server is manually shutdown by pressing enter, the *compiler* process is still running in the background. On Linux you can check this by typing `ps -e | grep omc` in the terminal. Currently the output looks like this:

```plain
   7287 ?        00:00:02 omc
```

The `omc` process is still running and must be killed manually by typing `kill 7287`. The server shutdown should already take care of this by sending the `exit()` command to the OMC.

**Comment by IlmarB** [comment]
Done - OMC is terminated after full shutdown
