### ISSUE TITLE
Add Modelica Standard Library to GitHub Actions

### ISSUE THREAD

**Issue by manuEbg** [MopeSWTP-SS21/MopeSWTP#79]
The Modelica Standard Library seems to not be available in our GitHubAction.

https://github.com/MopeSWTP-SS21/MopeSWTP/runs/2959630913#step:6:289

**Comment by CSchoel** [comment]
As is so often the case, you can take a peak at [MoST.jl's GH Actions script](https://github.com/THM-MoTE/ModelicaScriptingTools.jl/blob/6bf7423d51e8236f3a81b02e05fa79d9afdc1d7e/.github/workflows/test.yml#L33) to get an idea how to handle this. :wink:

**Comment by manuEbg** [comment]
see https://github.com/MopeSWTP-SS21/MopeSWTP/commit/a8d3401c872fb3f145ee6f1f203f154c80937f66
