### ISSUE TITLE
Grober Zeitplan

### ISSUE THREAD

**Issue by IlmarB** [MopeSWTP-SS21/MopeSWTP#8]
Bis nächsten Freitag hätte ich gerne einen groben Zeitplan, der folgende Punkte beinhaltet:

* Geplantes Projektende
    * vor den Prüfungswochen?
    * in der vorlesungsfreien Zeit?
* Eigene Rechnung, wie viele Stunden pro Woche von jedem Teammitglied zu absolvieren sind
    * 1 CrP = 30 Arbeitsstunden
    * 20 Stunden hätte ich für die Ausarbeitung der Projektpräsentation am Ende reserviert
* Geplante Deadline bis zum allerersten Prototyp
    * Funktionsumfang, den ich mir vorstelle: Ein Befehl kann per LSP an den Server geschickt werden und löst eine Reaktion beim Compiler aus (und sei es auch nur ein `getVersion()`).
    * Idealerweise existieren dazu dann auch schon Issues, die die einzelnen nötigen Arbeitspakete bis dort hin definieren.

**Comment by manuEbg** [comment]
9CrP * 30h = 270h

270h / 19 w ≈ 14 h/w

12.04.21 - 22.08.21

**Comment by CSchoel** [comment]
I have assigned myself here, because I have to find a date for the project presentation in our [KoBIS](http://kobis.thm.de/).

**Comment by manuEbg** [comment]
https://github.com/MopeSWTP-SS21/MopeSWTP/wiki/Schedule
