### ISSUE TITLE
Segment is missing in JSON RPC documentation

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#86]
The custom JSON RPC calls used by Mo|E all are under the segment `modelica/` (i.e. in vscode, I have to use the string `modelica/loadModel` as the "method", and not just `loadModel`). This information is missing in the wiki documentation.

**Comment by IlmarB** [comment]
Affirmative. Moved to "in Progress"

**Comment by IlmarB** [comment]
done, see wiki
